### ISSUE TITLE
v2.2.0'da yayınlanacak notlar

### ISSUE THREAD

**Issue by falsisdev** [falsisdev/falsisdb#12]
# v2.2.0
- db.sin(sayı)
> Girilen sayının sinüsünü alır.
```js
db.sin(90)//1
```
- db.cos(sayı)
> Girilen sayının kosinüsünü alır
```js
db.cos(90)//0
```
- db.pi
> Pi sayısını atar
```js
db.pi() //3,1415926
```
- db.euler
> Euler özdeşliğini atar
```js
db.euler
```
- db.rastgele(maxdeğer)
> Girilen değer en üst taban alınarak rastgele bir sayı söyler
```js
db.rastgele(32) //31
```
- db.mutlak(sayı)
> Girilen sayının mutlak değerini bulur |a|
```js
db.mutlak(-9) //9
```
- db.yuvarla(sayı)
> Girilen sayıyı en yakına yuvarlar
```js
db.yuvarla(9) //10
```
- db.kare(sayı)
> Girilen sayının karesini bulur
```js
db.kare(9) //81
```
- db.logaritma(sayı)
> Girilen sayının logaritmasını bulur
```js
db.logaritma(9)//2.1972245773362196
```
> =>
```js
//devamı gelecek (...)
```

**Comment by falsisdev** [comment]
> ✅ Tüm komutlara hata mesajları

**Comment by lunexdev** [comment]
v2.2.0 developers: lunex

**Comment by lunexdev** [comment]
bide şu an bunu bug olarak açıyorsun changelog.md dosyası aç

**Comment by falsisdev** [comment]
> bide şu an bunu bug olarak açıyorsun changelog.md dosyası aç

Kalsın

**Comment by falsisdev** [comment]
Büyük bir güncelleme olursa v2.0.0 yerine 2.5.0 bile yapabilirim

**Comment by lunexdev** [comment]
amk falsisi kendin method ekle artık

**Comment by falsisdev** [comment]
senden daha çok ekledim sus

**Comment by lunexdev** [comment]
sg benden çok eklemis tüm math methodları ve altyapı benim az method ekle

**Comment by falsisdev** [comment]
napim
