### ISSUE TITLE
Yapılacaklar Listesi

### ISSUE THREAD

**Issue by falsisdev** [falsisdev/falsisdb#19]
# Yapılacaklar
- [x] Event sistemlerine `%key%` `%value%` gibi fonksiyonlar eklenecek
- [x] Bozuk veya hatalı komutlar düzeltilecek
- [x] README.md değiştirilecek
- [x] Falsisdb Belgeler eklenecek
- [x] Falsisdb logosu hazırlanacak :)
- [x] Dosya düzeni değiştirlecek
- [x] Yeni versiyon yayınlanacak

**Her yapılan işlemi "✓" atarak belirteceğim.**
**Eklemek istediğiniz varsa yorum olarak aşağıya bırakabilirsiniz.**

**Comment by falsisdev** [comment]
Örnek Logo;
> ![Falsisdb](https://user-images.githubusercontent.com/63756985/122278411-893e5000-ceef-11eb-8e89-43e2d25d0c31.png)

**Comment by lunexdev** [comment]
good logo

**Comment by lunexdev** [comment]
bide dosya düzenini değiştircez onuda ekle

**Comment by falsisdev** [comment]
> bide dosya düzenini değiştircez onuda ekle

ekledim
