### ISSUE TITLE
çoklu işlem 4*8/2 gibi

### ISSUE THREAD

**Issue by WinBOT31sj** [falsisdev/falsisdb#32]
Başlığı Okuu
```

**Comment by WinBOT31sj** [comment]
bence çoksel olr

**Comment by falsisdev** [comment]
[Burada](https://github.com/falsisdev/falsisdb/pull/3), [Burada](https://github.com/falsisdev/falsisdb/pull/7) ve [Burada](https://github.com/falsisdev/falsisdb/pull/8) benzer methodlar eklenmişti. Ancak modül bir JSON database modülü olduğu için ve matematik işlemleri zaten JavaScript programlama dili içerisinde `2  + 2 * 3` gibi yapılabildiği için gereksiz buldum ve [Burada](https://github.com/falsisdev/falsisdb/commit/f61984522e9956432fad93a036cf50dd38636c01) kaldırdım. Bu sebeple reddedildi.

**Comment by falsisdev** [comment]
Ek olarak zaten `<db>.math()` fonksiyonu bulunmakta.

**Comment by falsisdev** [comment]
Daha fazla bilgi için [Belgelerden](https://docs.falsisdb.ml) fonksiyonları incelemeni öneririm.

**Comment by Wasp2021** [comment]
@falsisdev neden depolarımda burası gözüküyor

**Comment by falsisdev** [comment]
@Wasp2021 gözükmüyor?

**Comment by Wasp2021** [comment]
ss atabilirim @falsisdev

**Comment by Wasp2021** [comment]
@falsisdev 
![image](https://user-images.githubusercontent.com/82215788/128249906-abd46b5e-5e6f-4db6-8a62-4326d91da5ec.png)

**Comment by falsisdev** [comment]
Repolarını zaten görebiliyorum

**Comment by Wasp2021** [comment]
hayır senin repon neden bende var

**Comment by falsisdev** [comment]
@Wasp2021 bu benim repom :D?

**Comment by Wasp2021** [comment]
bu issues i tamamen kapatabilirmisin

**Comment by Wasp2021** [comment]
@falsisdev diyorum ki

**Comment by falsisdev** [comment]
@Wasp2021 kapalı zaten

**Comment by Wasp2021** [comment]
![image](https://user-images.githubusercontent.com/82215788/128250097-af69ee98-171c-494a-bc86-1626430ffa95.png)

**Comment by Wasp2021** [comment]
neden benim depolarım arasında var :D?

**Comment by Wasp2021** [comment]
@falsisdev tamamen sil kimse okuyamasın
issuesden kaynaklı bence

**Comment by falsisdev** [comment]
O senin repon değil sadece son etkileşimde bulunduğun repolar. Githubı incele :)

**Comment by Wasp2021** [comment]
onu nasıl kaldırabilirim @falsisdev

**Comment by falsisdev** [comment]
Sanırım istediğin buydu, tamamen kilitledim. Ama bir şey değişmeyecek
