### ISSUE TITLE
Geliştiriler tarafından Belirlenen Başlıca Sorunlar.

### ISSUE THREAD

**Issue by falsisdev** [falsisdev/falsisdb#36]
# Geliştiriler Tarafından Belirlenen Başlıca Sorunlar.

Son Güncelleme tarihi 5 Temmuz 2021'den beri hiçbir geliştiricinin elini sürmediği pakette uzun sürede oluşan hatalar:

- Belgeler ile ilgili hata:
`/src/index.js` satır 340-418 arası fonksiyonlar belgelerde bulunmuyor.

Düzeltme için belirlenen ortalama tarih: `06.06.2022 Pazartesi`

Ek: Sunucu fonksiyonları ayrı dosyalara alınıp düzenlenecek.

**Comment by falsisdev** [comment]
İlgili Geliştiriciler: @falsisdev, @berat141

**Comment by iamashley0** [comment]
about that event issue,you are closing your on call before passing the function as an argument.

**Comment by falsisdev** [comment]
> 

Yani sorun benden kaynaklanıyor? Pakette bir sorun yok? (Türkçe yaz paket Türkçe sadece commitleri ingilizce atıyorum)

**Comment by iamashley0** [comment]
```js
/*
 * Note the change here, the parenthesis is moved after
 * the function declaration so your anonymous function is now
 * passed as an argument.
 */
 db.on({
       type: "ready",
	status:"aktif",
	code:`console.log("Ready eventi çalışıyor")`
});
```

**Comment by iamashley0** [comment]
see more about it, [here](https://stackoverflow.com/questions/51898056/typeerror-err-invalid-arg-type-the-listener-argument-must-be-of-type-functi#51898234)

**Comment by falsisdev** [comment]
Unsolved Problems will be resolved ASAP
